// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
)

type Pokemon struct {
	Natdexnum      int32
	Name           string
	Gen            int32
	Spriteurl      string
	Spritelocation string
}

type PokemonType struct {
	ID        int32
	Natdexnum sql.NullInt32
	Typeid    sql.NullInt32
}

type Type struct {
	ID      int32
	Name    string
	Logourl string
}
