// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: pokemon.sql

package database

import (
	"context"

	"github.com/lib/pq"
)

const getAllPokemon = `-- name: GetAllPokemon :many
SELECT natdexnum, name, gen, spriteurl, spritelocation FROM pokemon
ORDER BY natDexNum
`

func (q *Queries) GetAllPokemon(ctx context.Context) ([]Pokemon, error) {
	rows, err := q.db.QueryContext(ctx, getAllPokemon)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Pokemon
	for rows.Next() {
		var i Pokemon
		if err := rows.Scan(
			&i.Natdexnum,
			&i.Name,
			&i.Gen,
			&i.Spriteurl,
			&i.Spritelocation,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAvailableGens = `-- name: GetAvailableGens :many
SELECT DISTINCT gen FROM pokemon
`

func (q *Queries) GetAvailableGens(ctx context.Context) ([]int32, error) {
	rows, err := q.db.QueryContext(ctx, getAvailableGens)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var gen int32
		if err := rows.Scan(&gen); err != nil {
			return nil, err
		}
		items = append(items, gen)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPokemonByGen = `-- name: GetPokemonByGen :many
SELECT natdexnum, name, gen, spriteurl, spritelocation FROM pokemon
WHERE gen = ANY($1::int[])
ORDER BY natDexNum
`

func (q *Queries) GetPokemonByGen(ctx context.Context, gens []int32) ([]Pokemon, error) {
	rows, err := q.db.QueryContext(ctx, getPokemonByGen, pq.Array(gens))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Pokemon
	for rows.Next() {
		var i Pokemon
		if err := rows.Scan(
			&i.Natdexnum,
			&i.Name,
			&i.Gen,
			&i.Spriteurl,
			&i.Spritelocation,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
