// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: types.sql

package database

import (
	"context"
	"database/sql"
)

const getAllPokemonTypes = `-- name: GetAllPokemonTypes :many
SELECT a.name, b.natDexNum, a.logoLocation 
FROM types a, pokemon_types b 
WHERE a.id = b.typeId ORDER BY b.id
`

type GetAllPokemonTypesRow struct {
	Name         string
	Natdexnum    sql.NullInt32
	Logolocation string
}

func (q *Queries) GetAllPokemonTypes(ctx context.Context) ([]GetAllPokemonTypesRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllPokemonTypes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllPokemonTypesRow
	for rows.Next() {
		var i GetAllPokemonTypesRow
		if err := rows.Scan(&i.Name, &i.Natdexnum, &i.Logolocation); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
